CAMPOS_TED = [
    "publication-number",
    "publication-date",
    "notice-title",
    "notice-type",
    "buyer-name",
    "buyer-country",
    "winner-name",
    "winner-identifier",
    "winner-decision-date",
    "result-value-notice",
    "result-value-cur-notice",
    "result-value-lot",
    "result-value-cur-lot",
    "total-value",
    "total-value-cur",
]
